### ISSUE TITLE
Parameters for paper?

### ISSUE THREAD

**Issue by benlansdell** [bcrafton/ssdfa#1]
Hi, are the parameters in results.py the ones that should reproduce the results in the paper?

I find, for instance, that running cifar10_conv.py with the DFA parameters in results.py does not reproduce the test accuracy in Table IV of the paper (https://arxiv.org/pdf/1903.02083.pdf).

Is it possible to have the parameters that do reproduce the paper's results?

Thanks,
Ben

**Comment by bcrafton** [comment]
sorry about the delay. working on this

**Comment by benlansdell** [comment]
No worries

**Comment by bcrafton** [comment]
Pushed an update! Everything is working for me. One thing it may have been is that different versions of keras import cifar10 and cifar100 in different ways (NHWC, NCHW) which can cause really bad performance. I put assertions in so this does not happen

**Comment by benlansdell** [comment]
Ah that's great, thanks for working on this!
